name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up XVFB
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -ac &
          sleep 5
     

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f
        continue-on-error: true

      - name: Capture Screenshots
        run: |
          mkdir -p screenshots
          for i in {1..10} # Capture screenshots for 10 seconds (adjust as needed)
          do
            xwd -root -out screenshots/screenshot_$i.xwd
            sleep 1
          done
        continue-on-error: true

      - name: Convert Screenshots to PNG
        run: |
          mkdir -p screenshots_png
          for file in screenshots/*.xwd
          do
            convert $file screenshots_png/$(basename $file .xwd).png
          done
        continue-on-error: true

      - name: Upload Screenshots as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots_png
