name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: self-hosted # Use a self-hosted runner for this job

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress Tests
        run: |
         xvfb-run -a npx cypress run --spec "cypress/integration/github_actions_spec.js"


      - name: Upload Cypress Screenshots as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
