name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest]  # Use the OS of your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Start OBS Studio Recording
        run: |
          
          # Start OBS Studio with recording settings
          /usr/share/man/man1/obs.1.gz --startrecording  > obs_log.txt 2>&1
          sleep 10  # Adjust as needed to allow OBS to start recording

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f

      - name: Stop OBS Studio Recording
        run: |
          # Stop OBS Studio recording
          obs --stoprecording
          sleep 10  # Adjust as needed to allow OBS to stop recording
