name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --user root  # This allows running commands as the root user

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asciinema
        run: |
          apt-get update
          apt-get install -y asciinema
        shell: bash

      - name: Start Screen Recording
        run: |
          asciinema rec recording.json
        shell: bash

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts && bash main.sh -f
        shell: bash

      - name: Stop Screen Recording
        run: |
          exit
        shell: bash

      - name: Upload Screen Recording
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: recording.json
