name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Run a Script
        run: cd /home/ubuntu/actions-runner/scripts && bash main.sh -f

  cypress-run:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          record: true
      - name: Run Cypress tests
        run: npm run cypress
