name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install xvfb -y
          sudo apt-get install x11-xserver-utils -y
          sudo Xvfb :99 -ac -screen 0 1280x1024x16 &
          export DISPLAY=:99

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f

      - name: Capture Job Logs Screenshots
        run: |
          mkdir -p artifacts/screenshots
          jobs=$(jobs -p)
          for job in $jobs; do
            xwd -root -silent -display $DISPLAY | xwdtopnm | pnmtopng > artifacts/screenshots/job_$job.png
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: artifacts/screenshots
