name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asciinema
        run: |
          sudo apt-get update
          sudo apt-get install asciinema
          # You might need to adjust the installation command for non-Ubuntu systems.

      - name: Start Recording
        run: asciinema rec recording.cast

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f

      - name: Stop Recording
        run: asciinema upload recording.cast
