name: Todo Node12 CICD
'on':
  push:
    branches:
      - master
jobs:
  run_script:
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Run a Script
        run: cd /home/ubuntu/actions-runner/scripts && bash main.sh -f
      - name: Install screen recording software
        uses: actions/setup-recording@v1
      - name: Start screen recording
        run: screenrec
      - name: Stop screen recording
        run: screenrec stop
      - name: Upload screen recording
        uses: actions/upload-artifact@v1
        with:
         name: screenrecording
         path: ./recording.mp4
