name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f
        continue-on-error: true

      - name: Capture Screenshots
        if: ${{ always() }}
        run: |
          # Replace this command with a screenshot capture command suitable for your OS.
          # Example for Linux:
          sudo apt-get update
          sudo apt-get install -y firefox xvfb
          xvfb-run --server-args="-screen 0 1024x768x24" firefox &
          sleep 5
          firefox --screenshot /path/to/screenshot.png
        continue-on-error: true

      - name: Upload Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /path/to/screenshot.png
