name: PROD-1. Start self-hosted builder
on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-1                
  
jobs:
  DeployOnEC2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Start self-hosted builder
        run: |
          aws ec2 start-instances --instance-id i-07af05ec4abaa6f9b
