name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f

      # Capture all action job logs and store them as an artifact
      - name: Archive job logs
        uses: actions/upload-artifact@v2
        with:
          name: job-logs
          path: ${{ runner.workspace }}
