name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Run a Script
        run: cd /home/ubuntu/actions-runner/scripts && bash main.sh -f

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress Tests
        run: |
         cd /home/ubuntu/app/node-todo
         xvfb-run -a npx cypress run --spec "cypress/integration/github_actions_spec.js"

      - name: Upload Cypress Screenshots as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
