name: Todo Node12 CICD

on:
  push:
    branches:
        - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']
        
    steps:
      - name: Run a Script
        run: cd /home/ubuntu/actions-runner/scripts && bash main.sh -f
      - name: Capture Log Screenshot
        uses: wei/capture-action-logs@v1
        with:
          file: logs.png

      - name: Upload Log Screenshot
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs.png
