name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f
        continue-on-error: true

      - name: Capture Screenshots
        uses: krtkush/screenshot-action@v2
        with:
          path: /home/ubuntu/actions-runner/scripts  # Adjust this path to match where your actions logs are generated
          filename: screenshots.zip

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs-artifact
          path: /home/ubuntu/actions-runner/scripts  # Adjust this path to match where your actions logs are generated
