name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ${{ runner.workspace }}/actions-runner/scripts/logs
