name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: self-hosted # Use a self-hosted runner for this job

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a Script
        run: |
          # Replace 'YOUR_COMMANDS_HERE' with your actual commands
          cd /home/ubuntu/actions-runner/scripts && bash main.sh -f
          
          # Record job logs to a file
          mkdir -p logs
          exec &> logs/job.log
          YOUR_COMMANDS_HERE

      - name: Upload Job Logs
        uses: actions/upload-artifact@v2
        with:
          name: job-logs
          path: logs/
