name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Log Directory
        run: mkdir -p ${{ runner.workspace }}/logs

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f | tee ${{ runner.workspace }}/logs/workflow.log

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ${{ runner.workspace }}/logs
