name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts && bash min.sh -f
        continue-on-error: true  # Continue even if the script fails

      - name: Capture Logs
        id: capture-logs
        run: |
          # Redirect the job logs to a file
          exec > logs.txt 2>&1
          
          # Run the script (if you want to capture its output)
          cd /home/ubuntu/actions-runner/scripts && bash main.sh -f
        continue-on-error: true
        if: always()  # Ensure this step runs even if previous steps fail

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs.txt
