name: Todo Node12 CICD

on:
  push:
    branches:
        - master

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64','node12.x']
        
    steps:
      - name: Run a Script
        run: cd /home/ubuntu/actions-runner/scripts && bash main.sh
