name: CICD for Project

on:
  push:
    branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run test

  depoly:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
     - name: Setup SSH key
       run: |
         echo "-----BEGIN OPENSSH PRIVATE KEY-----
               b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
               QyNTUxOQAAACAJlGtJBIQJiqusaNQrWNkCC5N9ZthchIcL7MAD0HWVqAAAAKDQRzZ50Ec2
               eQAAAAtzc2gtZWQyNTUxOQAAACAJlGtJBIQJiqusaNQrWNkCC5N9ZthchIcL7MAD0HWVqA
               AAAEC55VLRgjv4QjKYhJN9gCHgviMkhWcquLRfp021QINP6QmUa0kEhAmKq6xo1CtY2QIL
               k31m2FyEhwvswAPQdZWoAAAAG25pc2hpdC5yYWphbmkxOTA3QGdtYWlsLmNvbQEC
               -----END OPENSSH PRIVATE KEY-----" > key.pem
         chmod 600 key.pem
         eval $(ssh-agent)
         ssh-add key.pem

     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

               nvm install 12
               npm install -g pm2
               cd ~/node-todo
               git pull origin master
               npm install
               npm run test
               pm2 restart app
            
