name: Todo Node12 CICD

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ['self-hosted', 'Linux', 'X64']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your repository code
      
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y
      
      - name: Run a Script
        run: |
          cd /home/ubuntu/actions-runner/scripts
          bash main.sh -f
          
      - name: Create Video Artifact
        run: |
          # Add the 'ffmpeg' command to capture the video here
          # Replace the following with your actual capture command
          ffmpeg -f x11grab -video_size 1920x1080 -framerate 30 -i :0.0 -t 10 output.mp4

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v2
        with:
          name: job-artifacts
          path: output.mp4
