name: todo
on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ['self-hosted','Linux','X64']
    steps:
      - name: run a script
        run: cd /home/ubuntu/project/actions-runner/scripts/ && bash todo.sh
